language: python
python:
  - 3.4
  - 3.5

env:
  # Run unit test suite for all Python versions
  - CI_STEP=unit

matrix:
  include:

    # Run integration test suite with one Python version only, as it will use
    # Python version provided by Alpine Linux anyway (see
    # tests/integration/Dockerfile)
    - python: 3.5
      env: CI_STEP=integration DOCKER_VERSION=1.10
    - python: 3.5
      env: CI_STEP=integration DOCKER_VERSION=1.9
    - python: 3.5
      env: CI_STEP=integration DOCKER_VERSION=1.8
    - python: 3.5
      env: CI_STEP=integration DOCKER_VERSION=1.7
    - python: 3.5
      env: CI_STEP=integration DOCKER_VERSION=1.6
    # Docker HUB does not support 1.5 clients and older
    # https://forums.docker.com/t/docker-pull-deprecation-for-for-v1-5-clients

    # PEP8 checking
    - python: 3.5
      env: CI_STEP=style

dist: trusty
sudo: required
services:
  - docker
install:
  - pip install -r requirements.txt -r tests/requirements.txt

script:
  - ./ci-step.sh ${CI_STEP}

after_success:
  - pip install coveralls codacy-coverage
  - coveralls
  - test -n "$CODACY_PROJECT_TOKEN" -a
         "$CI_STEP" = "unit" -a
         "$TRAVIS_PYTHON_VERSION" = "3.5" &&
    python-codacy-coverage -r coverage.xml -c $TRAVIS_COMMIT
